version: "3"

services:
  
  db:
    container_name: 'intranet'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3307"
    ports:
      - "3307:3307"
    environment: 
      - MYSQL_DATABASE=intranet
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      db:
        condition: service_healthy
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/index